// <auto-generated />
namespace Tienda_compu.Migrations.StoreContex
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NotacionesOrden : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NotacionesOrden));
        
        string IMigrationMetadata.Id
        {
            get { return "201612082050076_NotacionesOrden"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
