// <auto-generated />
namespace Tienda_compu.Migrations.StoreContex
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class CarrtioAgregado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CarrtioAgregado));
        
        string IMigrationMetadata.Id
        {
            get { return "201612080448351_CarrtioAgregado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
